# Generated by Django 3.2.4 on 2021-10-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cpic', models.ImageField(default='', upload_to='static/category/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cpic', models.ImageField(default='', upload_to='static/courses')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpic', models.ImageField(default='', upload_to='static/faculty/')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=200)),
                ('gpic', models.ImageField(default='', upload_to='static/gallery')),
                ('gdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=60)),
                ('ppic', models.ImageField(default='', upload_to='static/profile/')),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rpic', models.ImageField(default='', upload_to='static/recruiters')),
                ('rdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=80)),
                ('cmpname', models.CharField(max_length=80)),
                ('cmplogo', models.ImageField(default='', upload_to='static/placement/')),
                ('city', models.CharField(max_length=100)),
                ('pyear', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('stupic', models.ImageField(default='', upload_to='static/studentnpic/')),
                ('pdate', models.DateField()),
                ('pcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpic', models.ImageField(default='', upload_to='static/fees/')),
                ('branch1', models.CharField(max_length=80)),
                ('branch2', models.CharField(max_length=80)),
                ('branch3', models.CharField(max_length=80)),
                ('hodname', models.CharField(max_length=80)),
                ('seats', models.CharField(max_length=100)),
                ('cfee', models.IntegerField()),
                ('eligibility', models.CharField(max_length=200)),
                ('due', models.CharField(max_length=100)),
                ('sdate', models.DateField()),
                ('pdate', models.DateField()),
                ('pcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
        ),
    ]
